markdown: rdiscount
permalink: /:title/
url: http://blog.younglau.info
name: 江南伪文艺范
author: YoungLau
qq: 
email: i@younglau.info
duoshuo: younglau
beian: 
cnzz: 1254162141
weibo: 3177171815
github: younglau182
pygments: true
safe: true
paginate: 20
about: "Github上的Blog  Jekyll @ GitHub"
